[build]
target = "thumbv7em-none-eabihf" # Cortex-M4F and Cortex-M7F (with FPU)

[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "arm-none-eabi-gdb -q -x ../openocd.gdb"

# probe-rs cannot disconnect gracefully --> we need to power off the device
#runner = "probe-rs run --chip STM32F767ZI"

[env]
DEFMT_LOG = "trace"
